// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKJaIcpIBW7ni-XaKf1bgyHm0Ny-wrGNM',
    appId: '1:201973054322:web:ea6546f0c98b6e7f40fbeb',
    messagingSenderId: '201973054322',
    projectId: 'vivencias-23bb5',
    authDomain: 'vivencias-23bb5.firebaseapp.com',
    storageBucket: 'vivencias-23bb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX9Hdd5RB8IcK34uzzk3v-2vWJAXW32-g',
    appId: '1:201973054322:android:5e40a70a74a904f940fbeb',
    messagingSenderId: '201973054322',
    projectId: 'vivencias-23bb5',
    storageBucket: 'vivencias-23bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGogjxNw1ncsivajntDWRHJ0iS9ynK8mY',
    appId: '1:201973054322:ios:14abcabaaa2e319d40fbeb',
    messagingSenderId: '201973054322',
    projectId: 'vivencias-23bb5',
    storageBucket: 'vivencias-23bb5.appspot.com',
    iosBundleId: 'com.example.war20220037',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGogjxNw1ncsivajntDWRHJ0iS9ynK8mY',
    appId: '1:201973054322:ios:51e6b9adfa01806540fbeb',
    messagingSenderId: '201973054322',
    projectId: 'vivencias-23bb5',
    storageBucket: 'vivencias-23bb5.appspot.com',
    iosBundleId: 'com.example.war20220037.RunnerTests',
  );
}
